CREATE TABLE IF NOT EXISTS `tm_tasks` (
  `ID` bigint(20) NOT NULL,
  `sTextId` varchar(100) NOT NULL,
  `sSupportedLangProg` varchar(255) NOT NULL DEFAULT '*',
  `sAuthor` varchar(100) NOT NULL,
  `sAuthorSolution` varchar(100) NOT NULL,
  `bShowLimits` tinyint(1) NOT NULL DEFAULT '1',
  `bUserTests` tinyint(1) NOT NULL DEFAULT '1',
  `bChecked` tinyint(1) NOT NULL DEFAULT '0',
  `iEvalMode` tinyint(1) NOT NULL DEFAULT '0',
  `bUsesLibrary` tinyint(1) NOT NULL,
  `bUseLatex` tinyint(1) NOT NULL DEFAULT '0',
  `iTestsMinSuccessScore` tinyint(3) NOT NULL DEFAULT '100',
  `bIsEvaluable` tinyint(1) NOT NULL DEFAULT '1',
  `sTemplateName` varchar(100) NOT NULL DEFAULT '',
  `sTaskPath` varchar(100) NOT NULL COMMENT 'taskPath as documented in taskgrader',
  `iVersion` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `synchro` (`iVersion`),
  UNIQUE KEY `text_id` (`sTextId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
