CREATE TABLE `tm_tasks_tests` (
  `ID` bigint(20) NOT NULL,
  `idTask` bigint(20) NOT NULL,
  `idSubtask` bigint(20) DEFAULT NULL,
  `idSubmission` bigint(20) DEFAULT NULL,
  `sGroupType` enum('Example','User','Evaluation','Submission') NOT NULL DEFAULT 'User',
  `idUser` bigint(20) DEFAULT NULL,
  `idPlatform` bigint(20) DEFAULT NULL,
  `iRank` tinyint(3) NOT NULL DEFAULT '0',
  `bActive` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'current tab or not, relevant only with user tests',
  `sName` varchar(100) NOT NULL,
  `sInput` mediumtext DEFAULT NULL,
  `sOutput` mediumtext DEFAULT NULL,
  `iVersion` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `TaskGroupUserRank` (`idTask`,`sGroupType`,`idUser`,`iRank`,`idPlatform`),
  KEY `TestName` (`sName`),
  KEY `synchro` (`iVersion`),
  KEY `TaskGroup` (`idTask`,`sGroupType`),
  KEY `TaskGroupUser` (`idTask`,`sGroupType`,`idUser`,`idPlatform`),
  KEY `idUser` (`idUser`,`idPlatform`),
  KEY `idSubtask` (`idSubtask`),
  CONSTRAINT `tm_tasks_tests_subtask` FOREIGN KEY (`idSubtask`) REFERENCES `tm_tasks_subtasks` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `tm_tasks_tests_task` FOREIGN KEY (`idTask`) REFERENCES `tm_tasks` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8
